version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: converter_user
      POSTGRES_PASSWORD: converter_password
      POSTGRES_DB: converter

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U converter_user -d converter"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: converter_backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    environment:
      DB_HOST: postgres_db
    depends_on:
      - postgres
    command: ["node", "dist/main.js"]

volumes:
  postgres_data:
