@API_URL=http://localhost:3001/api/v1

### number to word ep

POST {{API_URL}}/convert HTTP/1.1
Content-Type: application/json

{
    "number": 1083044495
}

### GET last 5 conversions
GET {{API_URL}}/conversions HTTP/1.1
Content-Content-Type: application/json